### ISSUE TITLE
Roadmap to v0.2

### ISSUE THREAD

**Issue by semseysandor** [es-progress/ESubuntu#13]
Epic issue to reach 0.2

- [x] Create readme, license
    - [x] es-progress/shell#5
    - [x] es-progress/shell#3
    - [x] es-progress/uranos#1
- [x] Move all possible settings to config files
- [x] Move most scripts to ESubuntu
- [x] Restructure scripts

**Comment by semseysandor** [comment]
Done
